const TOKENS_ACTION_TYPES = {
  GET_PTOKEN_LIST: '[TOKENS] GET_PTOKEN_LIST',
  SET_PTOKEN_LIST: '[TOKENS] SET_PTOKEN_LIST',
  GET_CUSTOM_TOKEN_LIST: '[TOKENS] GET_CUSTOM_TOKEN_LIST',
  SET_CUSTOM_TOKEN_LIST: '[TOKENS] SET_CUSTOM_TOKEN_LIST',
};

export default TOKENS_ACTION_TYPES;
